import Link from 'next/link';
import styles from '../page.module.css';

export const evenemang = [
  // SPORT
  { namn: 'Mallorca 312 Cykellopp', datum: '25 april 2026', plats: 'Palma – runt ön', kategori: 'Sport', beskrivning: 'Världens mest populära cykellopp med 10 000 deltagare på 312 km runt hela Mallorca', länk: 'https://www.mallorca312.com', bild: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80' },
  { namn: 'Ironman 70.3 Mallorca', datum: '10 maj 2026', plats: 'Alcúdia', kategori: 'Sport', beskrivning: 'Ett av världens hårdaste triathlon – 1,9 km simning, 90 km cykling och 21 km löpning', länk: 'https://www.google.com/search?q=Ironman+70.3+Mallorca+2026', bild: 'https://images.unsplash.com/photo-1530549387789-4c1017266635?w=600&q=80' },
  { namn: 'PalmaVela Regatta', datum: 'Maj 2026', plats: 'Palma', kategori: 'Sport', beskrivning: 'Internationell segelregatta med tävlande från hela världen i Palmas vackra bukt', länk: 'https://www.google.com/search?q=PalmaVela+Regatta+Mallorca+2026', bild: 'https://images.unsplash.com/photo-1505118380757-91f5f5632de0?w=600&q=80' },
  { namn: 'Mallorca Olympic Triathlon', datum: '24 maj 2026', plats: 'Colònia Sant Jordi', kategori: 'Sport', beskrivning: 'Olympisk distans längs Mallorcas vackraste sydkust – öppen för alla nivåer', länk: 'https://www.google.com/search?q=Mallorca+Olympic+Triathlon+2026', bild: 'https://images.unsplash.com/photo-1452626038306-9aae5e071dd3?w=600&q=80' },
  { namn: 'Copa del Rey Segelregatta', datum: '1–8 augusti 2026', plats: 'Palma', kategori: 'Sport', beskrivning: 'Kunglig segelregatta – en av Europas mest prestigefyllda och äldsta kappseglingar', länk: 'https://www.google.com/search?q=Copa+del+Rey+Segelregatta+Mallorca+2026', bild: 'https://images.unsplash.com/photo-1540946485063-a40da27545f8?w=600&q=80' },
  { namn: 'Palma International Boat Show', datum: 'April 2026', plats: 'Palma', kategori: 'Sport', beskrivning: 'Medelhavsregionens ledande båtmässa med lyxyachter och segelbåtar', länk: 'https://www.google.com/search?q=Palma+International+Boat+Show+2026', bild: 'https://images.unsplash.com/photo-1567899378494-47b22a2ae96a?w=600&q=80' },
  { namn: 'Magaluf Half Marathon', datum: 'Oktober 2026', plats: 'Magaluf', kategori: 'Sport', beskrivning: 'Populärt halvmaraton längs Mallorcas sydvästra kust med havsutsikt hela vägen', länk: 'https://www.google.com/search?q=Magaluf+Half+Marathon+2026', bild: 'https://images.unsplash.com/photo-1452626038306-9aae5e071dd3?w=600&q=80' },
  { namn: 'Palma Marathon', datum: 'Oktober 2026', plats: 'Palma', kategori: 'Sport', beskrivning: 'Maratonlopp genom Palmas historiska gator och längs strandpromenaden', länk: 'https://www.google.com/search?q=Palma+Marathon+2026', bild: 'https://images.unsplash.com/photo-1452626038306-9aae5e071dd3?w=600&q=80' },
  { namn: 'Palma Boat Show', datum: 'November 2026', plats: 'Palma', kategori: 'Sport', beskrivning: 'Höstens stora båtmässa med lyxbåtar och marinautrustning', länk: 'https://www.google.com/search?q=Palma+Boat+Show+2026', bild: 'https://images.unsplash.com/photo-1567899378494-47b22a2ae96a?w=600&q=80' },
  { namn: 'Mallorca Cycling Challenge', datum: 'September 2026', plats: 'Serra de Tramuntana', kategori: 'Sport', beskrivning: 'Cykelutmaning i Tramuntana-bergen längs UNESCO-världsarvsleden', länk: 'https://www.google.com/search?q=Mallorca+cycling+challenge+2026', bild: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80' },
  // MUSIK
  { namn: 'Mallorca Live Festival', datum: '11–13 juni 2026', plats: 'Magaluf, Calvià', kategori: 'Musik', beskrivning: 'Mallorcas största musikfestival med 25 000 besökare och internationella toppakter', länk: 'https://www.mallorcalivefestival.com', bild: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=600&q=80' },
  { namn: 'Danzû Festival', datum: 'Augusti 2026', plats: 'Magaluf', kategori: 'Musik', beskrivning: 'Elektronisk musikfestival med världsstjärnor som Carl Cox och Richie Hawtin', länk: 'https://www.google.com/search?q=Danzu+Festival+Mallorca+2026', bild: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=600&q=80' },
  { namn: 'Klassisk musik i Son Marroig', datum: 'Juni–september 2026', plats: 'Deià', kategori: 'Musik', beskrivning: 'Högtidliga klassiska konserter i det vackra palatset Son Marroig med havsutsikt', länk: 'https://www.google.com/search?q=Son+Marroig+konserter+Mallorca+2026', bild: 'https://images.unsplash.com/photo-1507838153414-b4b713384a76?w=600&q=80' },
  { namn: 'Jazz Festival Pollença', datum: 'Juli–augusti 2026', plats: 'Pollença', kategori: 'Musik', beskrivning: 'Internationell jazzfestival i Pollença gamla stan med världkända artister', länk: 'https://www.google.com/search?q=Jazz+Festival+Pollenca+Mallorca+2026', bild: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=600&q=80' },
  { namn: 'Nacht des Ballermanns', datum: 'Juli 2026', plats: 'Playa de Palma', kategori: 'Musik', beskrivning: 'Ballermanns stora sommarnatt med musik, dans och festligheter', länk: 'https://www.google.com/search?q=Ballermann+Mallorca+2026', bild: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=600&q=80' },
  { namn: 'Festival de Música de Sóller', datum: 'Juli 2026', plats: 'Sóller', kategori: 'Musik', beskrivning: 'Intim musikfestival i apelsinlundarnas stad med klassiska och moderna verk', länk: 'https://www.google.com/search?q=Festival+Musica+Soller+Mallorca+2026', bild: 'https://images.unsplash.com/photo-1507838153414-b4b713384a76?w=600&q=80' },
  { namn: 'Open Air Konserter Palma', datum: 'Sommaren 2026', plats: 'Palma', kategori: 'Musik', beskrivning: 'Utomhuskonserter på Palmas torg och platser med spansk och internationell musik', länk: 'https://www.google.com/search?q=konserter+Palma+Mallorca+sommar+2026', bild: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=600&q=80' },
  { namn: 'Electrobeach Festival', datum: 'Juli 2026', plats: 'Port d\'Alcúdia', kategori: 'Musik', beskrivning: 'Elektronisk strandmusikfestival med DJs och artister på Alcúdias strand', länk: 'https://www.google.com/search?q=Electrobeach+Festival+Mallorca+2026', bild: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=600&q=80' },
  { namn: 'Festival Música Clàssica Alcúdia', datum: 'Augusti 2026', plats: 'Alcúdia', kategori: 'Musik', beskrivning: 'Klassisk musikfestival i Alcúdias medeltida amfiteater – en unik upplevelse', länk: 'https://www.google.com/search?q=Festival+Musica+Classica+Alcudia+2026', bild: 'https://images.unsplash.com/photo-1507838153414-b4b713384a76?w=600&q=80' },
  { namn: 'Julkonserter i La Seu', datum: 'December 2026', plats: 'Palma', kategori: 'Musik', beskrivning: 'Stämningsfulla julkonserter i Palmas magnifika katedral La Seu', länk: 'https://www.google.com/search?q=julkonsert+La+Seu+Palma+2026', bild: 'https://images.unsplash.com/photo-1512389142860-9c449e58a543?w=600&q=80' },
  // KULTUR
  { namn: 'Semana Santa – Påskveckan', datum: 'April 2026', plats: 'Hela ön', kategori: 'Kultur', beskrivning: 'Högtidliga processioner med levande ljus och traditionell musik genom gamla stadsdelar', länk: 'https://www.google.com/search?q=Semana+Santa+Mallorca+2026', bild: 'https://images.unsplash.com/photo-1555993539-1732b0258235?w=600&q=80' },
  { namn: 'Firó – Moros y Cristianos', datum: 'Maj 2026', plats: 'Sóller', kategori: 'Kultur', beskrivning: 'Spektakulär historisk strid mellan morer och kristna som återuppförs på gatorna i Sóller', länk: 'https://www.google.com/search?q=Firo+Soller+Mallorca+2026', bild: 'https://images.unsplash.com/photo-1555993539-1732b0258235?w=600&q=80' },
  { namn: 'Nit de Foc – Johannesnatten', datum: '23 juni 2026', plats: 'Hela ön', kategori: 'Kultur', beskrivning: 'Johannes-natten firas med eldshower, fyrverkerier och festligheter på stränder och torg', länk: 'https://www.google.com/search?q=Nit+de+Foc+Mallorca+2026', bild: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=600&q=80' },
  { namn: 'Festa de Sant Jaume', datum: '25 juli 2026', plats: 'Alcúdia', kategori: 'Kultur', beskrivning: 'Alcúdias stora sommarfestival med konserter, eldshower och historiska uppträdanden', länk: 'https://www.google.com/search?q=Festa+Sant+Jaume+Alcudia+2026', bild: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=600&q=80' },
  { namn: 'Art Palma Brunch', datum: 'Hösten 2026', plats: 'Palma', kategori: 'Kultur', beskrivning: 'Internationell konstmässa i Palma med gallerier och konstnärer från hela Europa', länk: 'https://www.google.com/search?q=Art+Palma+Brunch+2026', bild: 'https://images.unsplash.com/photo-1561214115-f2f134cc4912?w=600&q=80' },
  { namn: 'La Gran Verbena', datum: 'Augusti 2026', plats: 'Palma', kategori: 'Kultur', beskrivning: 'Sommarens största folkfest med spansk musik, dans och mat under bar himmel', länk: 'https://www.google.com/search?q=Gran+Verbena+Palma+Mallorca+2026', bild: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=600&q=80' },
  { namn: 'Fira del Ram – Nöjesfält', datum: 'April–maj 2026', plats: 'Palma', kategori: 'Kultur', beskrivning: 'Mallorcas traditionella nöjesfält med karuseller och folklig festivalstämning', länk: 'https://www.google.com/search?q=Fira+del+Ram+Palma+Mallorca+2026', bild: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=600&q=80' },
  { namn: 'Oktoberfest Mallorca', datum: 'Oktober 2026', plats: 'Santa Ponça & Palma', kategori: 'Kultur', beskrivning: 'Bayerskt öl, pretzel och Wiesn-stämning under Mallorcas solsken', länk: 'https://www.google.com/search?q=Oktoberfest+Mallorca+2026', bild: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=600&q=80' },
  { namn: 'Julmarknad Palma', datum: 'December 2026', plats: 'Palma', kategori: 'Kultur', beskrivning: 'Stämningsfull julmarknad på Plaza Mayor med hantverk, julbak och glögg', länk: 'https://www.google.com/search?q=julmarknad+Palma+Mallorca+2026', bild: 'https://images.unsplash.com/photo-1512389142860-9c449e58a543?w=600&q=80' },
  { namn: 'Revetla de Sant Antoni', datum: 'Januari 2027', plats: 'Sa Pobla', kategori: 'Kultur', beskrivning: 'Mallorcas mest spektakulära eldsfestival med demoner, lägereld och djurvälsignelser', länk: 'https://www.google.com/search?q=Sant+Antoni+Festival+Mallorca+2027', bild: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=600&q=80' },
  // MAT & DRYCK
  { namn: 'Skördefest & Vinmarknad Binissalem', datum: 'Oktober 2026', plats: 'Binissalem', kategori: 'Mat & Dryck', beskrivning: 'Mallorcas vingårdar firar skörden med vinprovningar, musik och lokala delikatesser', länk: 'https://www.google.com/search?q=Binissalem+vinmarknad+2026', bild: 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=600&q=80' },
  { namn: 'Ensaimada-festival', datum: 'Oktober 2026', plats: 'Palma', kategori: 'Mat & Dryck', beskrivning: 'Firande av Mallorcas mest ikoniska bakverk med provningar och bagartävlingar', länk: 'https://www.google.com/search?q=ensaimada+festival+Mallorca+2026', bild: 'https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=600&q=80' },
  { namn: 'Gastrofestival Palma', datum: 'Maj 2026', plats: 'Palma', kategori: 'Mat & Dryck', beskrivning: 'Veckolång matfestival med pop-up-restauranger, kockdueller och smakprovningar', länk: 'https://www.google.com/search?q=Gastrofestival+Palma+Mallorca+2026', bild: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=600&q=80' },
  { namn: 'Olivoljemässa Sóller', datum: 'November 2026', plats: 'Sóller', kategori: 'Mat & Dryck', beskrivning: 'Sóllerdalen firar sin olivoljeskord med provningar, guidade turer och marknad', länk: 'https://www.google.com/search?q=olivolja+messa+Soller+Mallorca+2026', bild: 'https://images.unsplash.com/photo-1474722883778-792e7990302f?w=600&q=80' },
  { namn: 'Tapas & Vinfestival Palma', datum: 'Juni 2026', plats: 'Palma', kategori: 'Mat & Dryck', beskrivning: 'Palmas bästa tapas-restauranger samlas för en helg av smak, vin och gemenskap', länk: 'https://www.google.com/search?q=tapas+festival+Palma+Mallorca+2026', bild: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=600&q=80' },
  { namn: 'Mallorquinsk Matmarknad', datum: 'Varje lördag', plats: 'Santa Maria del Camí', kategori: 'Mat & Dryck', beskrivning: 'Öns bästa lokala matmarknad med ekologiska grönsaker, ostar, charkuterier och bröd', länk: 'https://www.google.com/search?q=matmarknad+Santa+Maria+del+Cami+Mallorca', bild: 'https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=600&q=80' },
  { namn: 'Sobrasada-festival', datum: 'Oktober 2026', plats: 'Felanitx', kategori: 'Mat & Dryck', beskrivning: 'Firande av Mallorcas ikoniska kryddkorv med provningar, tävlingar och hantverk', länk: 'https://www.google.com/search?q=sobrasada+festival+Mallorca+2026', bild: 'https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?w=600&q=80' },
  { namn: 'Öppen Vingård – Portes Obertes', datum: 'Oktober 2026', plats: 'Binissalem & Pla', kategori: 'Mat & Dryck', beskrivning: 'Mallorcas vingårdar öppnar dörrarna för gratis provningar och guidade turer', länk: 'https://www.google.com/search?q=Portes+Obertes+vingard+Mallorca+2026', bild: 'https://images.unsplash.com/photo-1559519529-0936e4058364?w=600&q=80' },
  { namn: 'Seafood & Paella Festival', datum: 'Augusti 2026', plats: 'Port d\'Alcúdia', kategori: 'Mat & Dryck', beskrivning: 'Havets bästa råvaror möter Mallorcas matkultur i en stämningsfull hamnfestival', länk: 'https://www.google.com/search?q=seafood+festival+Alcudia+Mallorca+2026', bild: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=600&q=80' },
  { namn: 'Ölmarknad Palma', datum: 'September 2026', plats: 'Palma', kategori: 'Mat & Dryck', beskrivning: 'Hantverksröl från hela Spanien och lokala bryggerier samlas i Palma för en unik smakupplevelse', länk: 'https://www.google.com/search?q=beer+festival+Palma+Mallorca+2026', bild: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=600&q=80' },
  // MARKNAD
  { namn: 'Fira de Sineu – Onsdagsmarknad', datum: 'Varje onsdag', plats: 'Sineu', kategori: 'Marknad', beskrivning: 'Mallorcas äldsta och mest autentiska marknad sedan 1306 – levande djur, hantverk och mat', länk: 'https://www.google.com/search?q=Fira+de+Sineu+marknad', bild: 'https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=600&q=80' },
  { namn: 'Inca Lädermässa', datum: 'November 2026', plats: 'Inca', kategori: 'Marknad', beskrivning: 'Mallorcas berömda lädermässa med skor, väskor och läderprodukter till reapriser', länk: 'https://www.google.com/search?q=Inca+Ladermarknad+Mallorca+2026', bild: 'https://images.unsplash.com/photo-1555529669-e69e7aa0ba9a?w=600&q=80' },
  { namn: 'Pollença Antikmarknad', datum: 'Varje söndag', plats: 'Pollença', kategori: 'Marknad', beskrivning: 'Charmig antikmarknad på Pollenças vackra torg med fynd, konst och hantverk', länk: 'https://www.google.com/search?q=antikmarknad+Pollenca+Mallorca', bild: 'https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=600&q=80' },
  { namn: 'Santanyi Onsdags- och Lördagsmarknad', datum: 'Varje onsdag & lördag', plats: 'Santanyi', kategori: 'Marknad', beskrivning: 'En av öns mysigaste marknader med lokala producenter, keramik och textilier', länk: 'https://www.google.com/search?q=marknad+Santanyi+Mallorca', bild: 'https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=600&q=80' },
  { namn: 'Artà Tisdagsmarknad', datum: 'Varje tisdag', plats: 'Artà', kategori: 'Marknad', beskrivning: 'Autentisk lokal marknad i den historiska byn Artà med färska råvaror och hantverk', länk: 'https://www.google.com/search?q=marknad+Arta+Mallorca', bild: 'https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=600&q=80' },
  { namn: 'Alcúdia Tisdags- och Söndagsmarknad', datum: 'Varje tisdag & söndag', plats: 'Alcúdia', kategori: 'Marknad', beskrivning: 'Stor och livlig marknad utanför Alcúdias murar med kläder, mat och souvenirer', länk: 'https://www.google.com/search?q=marknad+Alcudia+Mallorca', bild: 'https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=600&q=80' },
  { namn: 'Hippiemarknaden Alcúdia Port', datum: 'Sommaren 2026', plats: 'Port d\'Alcúdia', kategori: 'Marknad', beskrivning: 'Färgglad kvällsmarknad med smycken, konst och handgjorda produkter vid strandpromenaden', länk: 'https://www.google.com/search?q=hippiemarknaden+Alcudia+Mallorca', bild: 'https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=600&q=80' },
  { namn: 'Julmarknad Palma (Marknad)', datum: 'December 2026', plats: 'Palma', kategori: 'Marknad', beskrivning: 'Stämningsfull julmarknad på Plaza Mayor med hantverk, juldekorationer och mallorquinska godsaker', länk: 'https://www.google.com/search?q=julmarknad+Palma+Mallorca+2026', bild: 'https://images.unsplash.com/photo-1512389142860-9c449e58a543?w=600&q=80' },
  { namn: 'Felanitx Söndagsmarknad', datum: 'Varje söndag', plats: 'Felanitx', kategori: 'Marknad', beskrivning: 'Stor och folkrik söndagsmarknad i inlandet med lokala livsmedel, kryddor och hantverk', länk: 'https://www.google.com/search?q=marknad+Felanitx+Mallorca', bild: 'https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=600&q=80' },
  { namn: 'Manacor Måndag-marknad', datum: 'Varje måndag', plats: 'Manacor', kategori: 'Marknad', beskrivning: 'Stor stadsmarknad i Mallorcas näst största stad – känd för pärlor, möbler och lokala råvaror', länk: 'https://www.google.com/search?q=marknad+Manacor+Mallorca', bild: 'https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=600&q=80' },
  // FAMILJ
  { namn: 'Fira del Ram – Nöjesfält', datum: 'April–maj 2026', plats: 'Palma', kategori: 'Familj', beskrivning: 'Mallorcas traditionella nöjesfält med karuseller, spel och sötsaker för hela familjen', länk: 'https://www.google.com/search?q=Fira+del+Ram+Palma+Mallorca+2026', bild: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=600&q=80' },
  { namn: 'Aqualand El Arenal – Säsongsöppning', datum: 'Maj 2026', plats: 'El Arenal', kategori: 'Familj', beskrivning: 'Mallorcas populäraste vattenpark öppnar för sommarsäsongen med nya attraktioner', länk: 'https://www.aqualand.es', bild: 'https://images.unsplash.com/photo-1530549387789-4c1017266635?w=600&q=80' },
  { namn: 'Coves del Drach – Sommarsäsong', datum: 'April–oktober 2026', plats: 'Porto Cristo', kategori: 'Familj', beskrivning: 'Dramatiska underjordiska grottor med konsert på världens största underjordiska sjö', länk: 'https://www.google.com/search?q=Coves+del+Drach+Mallorca', bild: 'https://images.unsplash.com/photo-1548013146-72479768bada?w=600&q=80' },
  { namn: 'Safari Zoo Porto Cristo', datum: 'Hela sommaren 2026', plats: 'Porto Cristo', kategori: 'Familj', beskrivning: 'Mallorcas populäraste djurpark med giraffer, lejon, elefanter och kamelridning', länk: 'https://www.google.com/search?q=Safari+Zoo+Porto+Cristo+Mallorca', bild: 'https://images.unsplash.com/photo-1504450758481-7338eba7524a?w=600&q=80' },
  { namn: 'Hidropark Alcúdia', datum: 'Juni–september 2026', plats: 'Alcúdia', kategori: 'Familj', beskrivning: 'Populär vattenpark norr om Alcúdia med vattenrutschkanor och barnpooler', länk: 'https://www.hidropark.com', bild: 'https://images.unsplash.com/photo-1530549387789-4c1017266635?w=600&q=80' },
  { namn: 'Palma Aquarium', datum: 'Hela året', plats: 'Palma', kategori: 'Familj', beskrivning: 'Ett av Europas mest imponerande akvarium med hajbassäng och tropiska rev', länk: 'https://www.palmaaquarium.com', bild: 'https://images.unsplash.com/photo-1559827291-72ee739d0d9a?w=600&q=80' },
  { namn: 'Marineland Mallorca', datum: 'Maj–oktober 2026', plats: 'Costa de Blanes', kategori: 'Familj', beskrivning: 'Delfinshow, pingviner och hajar – perfekt familjedag längs sydvästkusten', länk: 'https://www.marineland.es', bild: 'https://images.unsplash.com/photo-1559827291-72ee739d0d9a?w=600&q=80' },
  { namn: 'Coves d\'Artà', datum: 'April–oktober 2026', plats: 'Capdepera', kategori: 'Familj', beskrivning: 'Dramatiska grottor med stalaktiter och stalagmiter nära Mallorcas nordliga udde', länk: 'https://www.google.com/search?q=Coves+Arta+Mallorca', bild: 'https://images.unsplash.com/photo-1548013146-72479768bada?w=600&q=80' },
  { namn: 'Western Park Mallorca', datum: 'Sommaren 2026', plats: 'Magaluf', kategori: 'Familj', beskrivning: 'Vilda västern-tema med vattenrutschkanor, barnaktiviteter och western-shower', länk: 'https://www.westernpark.com', bild: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=600&q=80' },
  { namn: 'Falconeria de Altair', datum: 'Hela sommaren 2026', plats: 'Cas Concos', kategori: 'Familj', beskrivning: 'Spektakulärt falkneri med örnar, falkar och ugglor – unikt för barn och vuxna', länk: 'https://www.google.com/search?q=Falconeria+de+Altair+Mallorca', bild: 'https://images.unsplash.com/photo-1504450758481-7338eba7524a?w=600&q=80' },
];

export default function SectionEvents() {
  return (
    <section className={styles.eventsSection}>
      <div className={styles.eventsLeft}>
        <h2 className={styles.eventsTitle}>KOMMANDE EVENEMANG</h2>
        <p className={styles.eventsText}>Mallorca är värd till många evenemang under året – cykellopp, segelregattor, jordbruksmarknader och internationella sportevenemang.</p>
        <Link href="/evenemang" className={styles.eventsBtn}>Se alla evenemang</Link>
      </div>
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(260px, 1fr))', gap: '16px', flex: 1 }}>
        {evenemang.slice(0, 6).map((e, i) => (
          <div key={i} style={{ background: '#e0e0e0', borderRadius: '12px', overflow: 'hidden', boxShadow: '0 2px 12px rgba(0,0,0,0.08)', display: 'flex', flexDirection: 'column' }}>
            <img src={e.bild} alt={e.namn} style={{ width: '100%', height: '160px', objectFit: 'cover', display: 'block' }} />
            <div style={{ padding: '16px', flex: 1, display: 'flex', flexDirection: 'column', gap: '6px' }}>
              <div style={{ fontSize: '0.75rem', color: '#555', display: 'flex', gap: '8px', flexWrap: 'wrap', alignItems: 'center' }}>
                <span style={{ background: '#111', color: 'white', borderRadius: '4px', padding: '2px 8px', fontSize: '0.7rem', fontWeight: '600' }}>{e.kategori}</span>
                <span>📅 {e.datum}</span>
                <span>📍 {e.plats}</span>
              </div>
              <h3 style={{ fontSize: '1rem', fontWeight: '700', letterSpacing: '-0.02em', margin: 0, color: '#111' }}>{e.namn}</h3>
              <p style={{ fontSize: '0.85rem', color: '#444', lineHeight: '1.5', margin: 0, flex: 1 }}>{e.beskrivning}</p>
              <a href={e.länk} target="_blank" rel="noopener noreferrer" style={{ marginTop: '8px', display: 'inline-block', padding: '6px 14px', background: '#111', color: 'white', borderRadius: '6px', fontSize: '0.8rem', fontWeight: '600', textDecoration: 'none' }}>Läs mer ↗</a>
            </div>
          </div>
        ))}
      </div>
    </section>
  );
}
